/*
 * description: the types for all actions
 * author: 麦芽糖
 * time: 2017年03月18日14:03:11
 */

'use strict'

// bookDetailAction
export const BOOK_DETAIL = 'BOOK_DETAIL'
export const BOOK_DETAIL_LOADING = 'BOOK_DETAIL_LOADING'
export const BOOK_HOT_REVIEW = 'BOOK_HOT_REVIEW'
export const BOOK_RECOMMEND_BOOK_LIST = 'BOOK_RECOMMEND_BOOK_LIST'

// readPlatformAction
export const READ_BOOK_CHAPTER_LIST = 'READ_BOOK_CHAPTER_LIST'
export const READ_BOOK_CHAPTER_DETAIL = 'READ_BOOK_CHAPTER_DETAIL'

// discover -- charts
export const DISCOVER_CHARTS_LOADING = 'DISCOVER_CHARTS_LOADING'
export const DISCOVER_CHARTS = 'DISCOVER_CHARTS'
export const DISCOVER_CHARTS_DETAIL_LOADING = 'DISCOVER_CHARTS_DETAIL_LOADING'
export const DISCOVER_CHARTS_DETAIL = 'DISCOVER_CHARTS_DETAIL'

// discover -- bookList
export const DISCOVER_BOOK_LIST_LOADING = 'DISCOVER_BOOK_LIST_LOADING'
export const DISCOVER_BOOK_LIST = 'DISCOVER_BOOK_LIST'
export const DISCOVER_CATEGORY_LIST_LOADING = 'DISCOVER_CATEGORY_LIST_LOADING'
export const DISCOVER_CATEGORY_LIST = 'DISCOVER_CATEGORY_LIST'
export const DISCOVER_CATEGORY_LIST_V2 = 'DISCOVER_CATEGORY_LIST_V2'

// community -- community
export const COMMUNITY_BOOK_DISCUSSION_LIST_LOADING = 'COMMUNITY_BOOK_DISCUSSION_LIST_LOADING'
export const COMMUNITY_BOOK_DISCUSSION_LIST = 'COMMUNITY_BOOK_DISCUSSION_LIST'
export const COMMUNITY_BOOK_DISCUSSION_DETAIL_LOADING = 'COMMUNITY_BOOK_DISCUSSION_DETAIL_LOADING'
export const COMMUNITY_BOOK_DISCUSSION_DETAIL = 'COMMUNITY_BOOK_DISCUSSION_DETAIL'
export const COMMUNITY_BOOK_DISCUSSION_DETAIL_COMMENT_BEST = 'COMMUNITY_BOOK_DISCUSSION_DETAIL_COMMENT_BEST'
export const COMMUNITY_BOOK_DISCUSSION_DETAIL_COMMENT_LIST_LOADING = 'COMMUNITY_BOOK_DISCUSSION_DETAIL_COMMENT_LIST_LOADING'
export const COMMUNITY_BOOK_DISCUSSION_DETAIL_COMMENT_LIST = 'COMMUNITY_BOOK_DISCUSSION_DETAIL_COMMENT_LIST'

// community -- review
export const COMMUNITY_BOOK_REVIEW_LIST_LOADING = 'COMMUNITY_BOOK_REVIEW_LIST_LOADING'
export const COMMUNITY_BOOK_REVIEW_LIST = 'COMMUNITY_BOOK_REVIEW_LIST'
export const COMMUNITY_BOOK_REVIEW_DETAIL_LOADING = 'COMMUNITY_BOOK_REVIEW_DETAIL_LOADING'
export const COMMUNITY_BOOK_REVIEW_DETAIL = 'COMMUNITY_BOOK_REVIEW_DETAIL'
export const COMMUNITY_BOOK_REVIEW_DETAIL_COMMENT_BEST = 'COMMUNITY_BOOK_REVIEW_DETAIL_COMMENT_BEST'
export const COMMUNITY_BOOK_REVIEW_DETAIL_COMMENT_LIST_LOADING = 'COMMUNITY_BOOK_REVIEW_DETAIL_COMMENT_LIST_LOADING'
export const COMMUNITY_BOOK_REVIEW_DETAIL_COMMENT_LIST = 'COMMUNITY_BOOK_REVIEW_DETAIL_COMMENT_LIST'

// community -- review
export const COMMUNITY_BOOK_HELP_LIST_LOADING = 'COMMUNITY_BOOK_HELP_LIST_LOADING'
export const COMMUNITY_BOOK_HELP_LIST = 'COMMUNITY_BOOK_HELP_LIST'
export const COMMUNITY_BOOK_HELP_DETAIL_LOADING = 'COMMUNITY_BOOK_HELP_DETAIL_LOADING'
export const COMMUNITY_BOOK_HELP_DETAIL = 'COMMUNITY_BOOK_HELP_DETAIL'
export const COMMUNITY_BOOK_HELP_DETAIL_COMMENT_BEST = 'COMMUNITY_BOOK_HELP_DETAIL_COMMENT_BEST'
export const COMMUNITY_BOOK_HELP_DETAIL_COMMENT_LIST_LOADING = 'COMMUNITY_BOOK_HELP_DETAIL_COMMENT_LIST_LOADING'
export const COMMUNITY_BOOK_HELP_DETAIL_COMMENT_LIST = 'COMMUNITY_BOOK_HELP_DETAIL_COMMENT_LIST'
