/*
 * description: the types for all actions
 * author: 麦芽糖
 * time: 2017年03月18日14:03:11
 */

'use strict'

// search
export const SEARCH_HOT_WORDS = 'SEARCH_HOT_WORDS'
export const SEARCH_REFRESH_HOT_WORDS = 'SEARCH_REFRESH_HOT_WORDS'
export const SEARCH_AUTO_COMPLETE = 'SEARCH_AUTO_COMPLETE'
export const SEARCH_SEARCH_BOOKS = 'SEARCH_SEARCH_BOOKS'
export const SEARCH_BACK_TO_INIT_STATE = 'SEARCH_BACK_TO_INIT_STATE'

// bookDetailAction
export const BOOK_DETAIL = 'BOOK_DETAIL'
export const BOOK_DETAIL_LOADING = 'BOOK_DETAIL_LOADING'
export const BOOK_HOT_REVIEW = 'BOOK_HOT_REVIEW'
export const BOOK_RECOMMEND_BOOK_LIST = 'BOOK_RECOMMEND_BOOK_LIST'

// book -- bookCommunity
export const BOOK_DISCUSSION_LIST = 'BOOK_DISCUSSION_LIST'
export const BOOK_DISCUSSION_LIST_LOADING = 'BOOK_DISCUSSION_LIST_LOADING'
export const BOOK_REVIEW_LIST = 'BOOK_REVIEW_LIST'
export const BOOK_REVIEW_LIST_LOADING = 'BOOK_REVIEW_LIST_LOADING'

// readPlatformAction

// discover -- charts
export const DISCOVER_CHARTS_LOADING = 'DISCOVER_CHARTS_LOADING'
export const DISCOVER_CHARTS = 'DISCOVER_CHARTS'
export const DISCOVER_CHARTS_DETAIL_LOADING = 'DISCOVER_CHARTS_DETAIL_LOADING'
export const DISCOVER_CHARTS_DETAIL = 'DISCOVER_CHARTS_DETAIL'

// discover -- bookList
export const DISCOVER_BOOK_LIST_LOADING = 'DISCOVER_BOOK_LIST_LOADING'
export const DISCOVER_BOOK_LIST = 'DISCOVER_BOOK_LIST'
export const DISCOVER_CATEGORY_LIST_LOADING = 'DISCOVER_CATEGORY_LIST_LOADING'
export const DISCOVER_CATEGORY_LIST = 'DISCOVER_CATEGORY_LIST'
export const DISCOVER_CATEGORY_LIST_V2 = 'DISCOVER_CATEGORY_LIST_V2'

// community -- community
export const COMMUNITY_BOOK_DISCUSSION_LIST_LOADING = 'COMMUNITY_BOOK_DISCUSSION_LIST_LOADING'
export const COMMUNITY_BOOK_DISCUSSION_LIST = 'COMMUNITY_BOOK_DISCUSSION_LIST'
export const COMMUNITY_BOOK_DISCUSSION_DETAIL_LOADING = 'COMMUNITY_BOOK_DISCUSSION_DETAIL_LOADING'
export const COMMUNITY_BOOK_DISCUSSION_DETAIL = 'COMMUNITY_BOOK_DISCUSSION_DETAIL'
export const COMMUNITY_BOOK_DISCUSSION_DETAIL_COMMENT_BEST = 'COMMUNITY_BOOK_DISCUSSION_DETAIL_COMMENT_BEST'
export const COMMUNITY_BOOK_DISCUSSION_DETAIL_COMMENT_LIST_LOADING = 'COMMUNITY_BOOK_DISCUSSION_DETAIL_COMMENT_LIST_LOADING'
export const COMMUNITY_BOOK_DISCUSSION_DETAIL_COMMENT_LIST = 'COMMUNITY_BOOK_DISCUSSION_DETAIL_COMMENT_LIST'

// community -- review
export const COMMUNITY_BOOK_REVIEW_LIST_LOADING = 'COMMUNITY_BOOK_REVIEW_LIST_LOADING'
export const COMMUNITY_BOOK_REVIEW_LIST = 'COMMUNITY_BOOK_REVIEW_LIST'
export const COMMUNITY_BOOK_REVIEW_DETAIL_LOADING = 'COMMUNITY_BOOK_REVIEW_DETAIL_LOADING'
export const COMMUNITY_BOOK_REVIEW_DETAIL = 'COMMUNITY_BOOK_REVIEW_DETAIL'
export const COMMUNITY_BOOK_REVIEW_DETAIL_COMMENT_BEST = 'COMMUNITY_BOOK_REVIEW_DETAIL_COMMENT_BEST'
export const COMMUNITY_BOOK_REVIEW_DETAIL_COMMENT_LIST_LOADING = 'COMMUNITY_BOOK_REVIEW_DETAIL_COMMENT_LIST_LOADING'
export const COMMUNITY_BOOK_REVIEW_DETAIL_COMMENT_LIST = 'COMMUNITY_BOOK_REVIEW_DETAIL_COMMENT_LIST'

// community -- review
export const COMMUNITY_BOOK_HELP_LIST_LOADING = 'COMMUNITY_BOOK_HELP_LIST_LOADING'
export const COMMUNITY_BOOK_HELP_LIST = 'COMMUNITY_BOOK_HELP_LIST'
export const COMMUNITY_BOOK_HELP_DETAIL_LOADING = 'COMMUNITY_BOOK_HELP_DETAIL_LOADING'
export const COMMUNITY_BOOK_HELP_DETAIL = 'COMMUNITY_BOOK_HELP_DETAIL'
export const COMMUNITY_BOOK_HELP_DETAIL_COMMENT_BEST = 'COMMUNITY_BOOK_HELP_DETAIL_COMMENT_BEST'
export const COMMUNITY_BOOK_HELP_DETAIL_COMMENT_LIST_LOADING = 'COMMUNITY_BOOK_HELP_DETAIL_COMMENT_LIST_LOADING'
export const COMMUNITY_BOOK_HELP_DETAIL_COMMENT_LIST = 'COMMUNITY_BOOK_HELP_DETAIL_COMMENT_LIST'
